USE [todo_list_db]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WorkPlaces](
	[id_workplace] [int] NOT NULL,
	[name_workplace] [nchar](30) NOT NULL,
 CONSTRAINT [PK_Workplaces] PRIMARY KEY CLUSTERED 
(
	[id_workplace] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


